call plug#begin('~/.vim/plugged')

Plug 'junegunn/seoul256.vim'
Plug 'junegunn/fzf.vim'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-dispatch'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-obsession'
Plug 'tpope/vim-repeat'
Plug 'vim-airline/vim-airline'
Plug 'christoomey/vim-tmux-navigator'
Plug 'benmills/vimux'
Plug 'dense-analysis/ale'
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'SirVer/ultisnips'
"Plug 'tpope/vim-tbone'
"Plug 'tpope/vim-dadbod'
"Plug 'scrooloose/nerdtree'
"Plug 'morhetz/gruvbox'
call plug#end()
set statusline^=%{coc#status()}
inoremap <expr> <Tab> pumvisible() ? "\<C-n>" : "\<Tab>"
inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"
"inoremap <silent><expr> <cr> pumvisible() ? coc#_select_confirm() : "\<C-g>u\<CR>"
"[A same buffer] [B open buffers] [F filename completion]
":CocInstall coc-ultisnips
autocmd! CompleteDone * if pumvisible() == 0 | pclose | endif
"Temporary solution to load vimtex
"let &rtp = '~/.vim/pack/plugins/opt/vimtex,' . &rtp
"let &rtp .= ',~/.vim/pack/plugins/opt/vimtex/after'

syntax enable
filetype plugin indent on
"let g:gruvbox_italic=1
colorscheme seoul256
set background=dark

"Line below for starting vim with vimtex background compilation
"vim --servername NAME anotherTest.tex

"For fuzzy finding make sure I know where it is
set rtp+=/usr/local/opt/fzf

"When switch from vim save that current buffer if needed
let g:tmux_navigator_save_on_switch = 1

"Actually creates vertical split
let g:VimuxOrientation = "h"

let g:airline#extensions#tabline#enabled = 1
"let g:airline_extensions = []

let g:UltiSnipsExpandTrigger="<c-b>"
let g:UltiSnipsJumpForwardTrigger="<c-b>"
let g:UltiSnipsJumpBackwardTrigger="<c-y>"
let g:UltiSnipsEditSplit="vertical"

"let g:ycm_global_ycm_extra_conf = "~/.vim/.ycm_extra_conf.py"

let g:ale_completion_enabled = 1
"let g:ale_linters = {
"\   'javascript': ['jshint'],
"\ }
"nmap <silent> [W <Plug>(ale_first)
"nmap <silent> [w <Plug>(ale_previous)
"nmap <silent> ]w <Plug>(ale_next)
"nmap <silent> ]W <Plug>(ale_last)
"let g:ale_lint_on_text_changed = 'never'
"let g:ale_lint_on_save = 1
"let g:ale_lint_on_enter = 0
"let g:ale_lint_on_filetype_changed = 0

let g:vimtex_view_method='zathura'
let g:tex_flavor='latex'

set sessionoptions-=options

"find ctags for later
set tags+=./tags;/
"colo desert
set nocompatible
autocmd FileType c,cpp nnoremap <buffer> <Space>i :<C-u>w<CR>:Make<CR>
autocmd FileType c,cpp nnoremap <buffer> <Space>y :<C-u>call VimuxRunCommand("clear; ./" . expand("%:t:r"))<CR>
autocmd FileType python nnoremap <buffer> <Space>y :<C-u>call VimuxRunCommand("clear; python3 " . expand("%:t"))<CR>
autocmd FileType python setlocal tabstop=4 softtabstop=4 shiftwidth=4 textwidth=79 expandtab autoindent fileformat=unix
autocmd FileType make setlocal ts=8 sts=8 sw=8 noexpandtab
autocmd FileType javascript setlocal tabstop=2 softtabstop=2 shiftwidth=2 
autocmd FileType java setlocal tabstop=2 softtabstop=2 shiftwidth=2 
autocmd FileType html setlocal tabstop=2 softtabstop=2 shiftwidth=2 
autocmd FileType css setlocal tabstop=2 softtabstop=2 shiftwidth=2 

"for ale install linters
"npm install -g typescript
"pip3 install pylint
"augroup vimrc_autocmds
"    autocmd BufEnter * highlight OverLength ctermbg=red
"    autocmd BufEnter * match OverLength /\%80v.*/
"augroup END
set path+=**
"don't search tags on control p
set complete-=t
set encoding=utf-8
set fileencoding=utf-8
set complete-=i
set wrap
set textwidth=79
set formatoptions=qrn1
set autoindent
set autowrite
set number relativenumber
set hidden
"set tabstop=4
"set shiftwidth=4
set shiftround
set expandtab
set ignorecase
set smartcase
set scrolloff=3
set novisualbell
set wildmode=list:longest
set nohlsearch
set incsearch
set ruler
set backspace=indent,eol,start
"coc.nvim recommended settings
set cmdheight=2
set updatetime=300
set signcolumn=yes
set shortmess+=c
" Use tab for trigger completion with characters ahead and navigate.
" Use command ':verbose imap <tab>' to make sure tab is not mapped by other plugin.
inoremap <silent><expr> <TAB>
      \ pumvisible() ? "\<C-n>" :
      \ <SID>check_back_space() ? "\<TAB>" :
      \ coc#refresh()
inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<C-h>"

function! s:check_back_space() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~# '\s'
endfunction

cnoremap jk <Right><Right><C-u><C-h> 
nnoremap ,q /(<CR>:nohl<CR>
noremap ,e %
noremap ,s ^
noremap ,d $
noremap ,r #
noremap ,c *
nnoremap ,t zt
inoremap jk <Esc>:w<CR>
inoremap ,a <Esc>A
vnoremap v <Esc>
inoremap <C-n> <C-x><C-p>
nnoremap <C-p> :<C-u>FZF<CR>
"nnoremap <Space>o :<C-u>VimuxPromptCommand<CR>
"nnoremap <Space>u :<C-u>VimuxRunLastCommand<CR>
nnoremap <Space>c :<C-u>VimuxInspectRunner<CR>
nnoremap ,z :VimuxZoomRunner<CR>
nnoremap <C-y> 5<C-y>
nnoremap <C-u> 5<C-e>
noremap ' `
noremap ` '
"nnoremap <Space>a :%s/\<<C-r><C-w>\>//g<Left><Left>
nnoremap gp :bp<CR>
nnoremap go :bn<CR>
nnoremap gy <C-w>_
nnoremap gu <C-w>=
nnoremap gm <C-w><Bar>
nnoremap <Space>f /{<CR>:nohl<CR>
cnoremap %% <C-R>=fnameescape(expand('%:h')).'/'<cr>
map <Space>e :e %%
nnoremap ,r :ls<CR>:vsp<Space><Bar><Space>b<Space>
"nnoremap <Space>m :packadd nerdtree<CR>:NERDTreeToggle<CR>
nnoremap ,x :ls<CR>:bd<Space>
nnoremap ,n :cn<CR>
nnoremap ,p :cp<CR>
nnoremap ,; :cw<CR>
nnoremap ,. :cclose<CR>
nnoremap ,h <C-w>10<
nnoremap ,l <C-w>10>
nnoremap ,k <C-w>10+
nnoremap ,j <C-w>10-
noremap ,g G
noremap ,a A
noremap ,f F
noremap ,t T
nnoremap <Space>w :w<cr>
nnoremap <Space>q :wq<cr>
nnoremap ,z :only<CR>
"nnoremap <Space>t :q!
nnoremap <Space> :Buffers<cr>
nnoremap [ :GFiles<CR>
nnoremap ] :Rg

nnoremap ,x <C-w>x

"Commands for fugitive.vim plugin
nnoremap gjg :Git<Space> 
nnoremap gjw :Gwrite<CR><CR>
nnoremap gjc :Gread<CR>
nnoremap gjr :Gremove<CR>
nnoremap gjv :Gmove<Space>
nnoremap gjt :Gcommit<CR>
nnoremap gjb :Gblame<CR>
nnoremap gja :Gstatus<CR>
nnoremap gjs :Gpush<CR>
nnoremap gjl :Gpull<CR>
nnoremap ghh <C-w>H
nnoremap gjj <C-w>J
nnoremap gkk <C-w>K
nnoremap gll <C-w>L
noremap ,, ,
nnoremap zk O<Esc>j
nnoremap zj o<Esc>k
nnoremap <C-j> <C-w><C-j>
nnoremap <C-k> <C-w><C-k>
nnoremap <C-l> <C-w><C-l>
nnoremap <C-h> <C-w><C-h>
set splitbelow 
set splitright
set showmatch
let g:netrw_banner = 0
set laststatus=2
set statusline=%.30F
set statusline+=%=
set statusline+=%l
set statusline+=/
set statusline+=%L
"nnoremap =oa :setlocal nonumber<Space><bar><Space>:setlocal norelativenumber
"Thoughts for small buffer list transition to arglist
":arga %:ls<CR>:b 
"
"
